---
- name: Provision AWS Infrastructure
  hosts: localhost
  gather_facts: False
  vars:
    ec2_instance_type: t2.micro
    ec2_ami: ami-0d5d9d301c853a04a  # Ubuntu Server 20.04 LTS
    ec2_key_name: key_name  # Replace with AWS key pair name
    ec2_security_group: web_sg
    rds_instance_class: db.t2.micro
    rds_engine: mysql
    rds_db_name: myappdb
    rds_master_username: admin
    rds_master_password: My_password  # Replace with a secure password
    region: us-east-1  # Change to your preferred AWS region

  tasks:
    - name: Create EC2 security group
      ec2_group:
        name: "{{ ec2_security_group }}"
        description: Security group for web server
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0)
        state: present

    - name: Launch EC2 instance
      ec2:
        key_name: "{{ ec2_key_name }}"
        group: "{{ ec2_security_group }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_ami }}"
        wait: yes
        region: "{{ region }}"
        count: 1
        instance_tags:
          Name: web_server
      register: ec2

    - name: Add tag to EC2 instance
      ec2_tag:
        region: "{{ region }}"
        resource: "{{ item.id }}"
        state: present
        tags:
          Name: web_server
      loop: "{{ ec2.instances }}"

    - name: Create RDS security group
      ec2_group:
        name: rds_sg
        description: Security group for RDS instance
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 3306
            group_name: "{{ ec2_security_group }}"
        state: present

    - name: Create RDS instance
      rds:
        command: create
        instance_name: mydbinstance
        db_instance_class: "{{ rds_instance_class }}"
        engine: "{{ rds_engine }}"
        allocated_storage: 20
        master_username: "{{ rds_master_username }}"
        master_user_password: "{{ rds_master_password }}"
        db_name: "{{ rds_db_name }}"
        region: "{{ region }}"
        vpc_security_groups: [ "rds_sg" ]
        wait: yes
        state: present
